# Generated by Django 5.0.2 on 2024-02-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isimm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
