# Generated by Django 5.0.2 on 2024-02-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isimm', '0002_remove_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
    ]
