# Generated by Django 5.0.2 on 2024-02-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isimm', '0005_enseignant_is_head_of_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='cycle_ingenieur_type',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='cycle_preparatoire_type',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='license_type',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='master_type',
        ),
        migrations.AddField(
            model_name='formation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='type',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
    ]
