# Generated by Django 5.0.2 on 2024-02-21 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isimm', '0006_remove_formation_cycle_ingenieur_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='is_head_of_department',
        ),
        migrations.AlterField(
            model_name='department',
            name='chef_department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_chef', to='isimm.enseignant'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='cv',
            field=models.URLField(blank=True, null=True),
        ),
    ]
