# Generated by Django 5.0.2 on 2024-02-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isimm', '0007_remove_enseignant_is_head_of_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='nom',
            field=models.CharField(choices=[('DÉPARTEMENT INFORMATIQUE', 'DÉPARTEMENT INFORMATIQUE'), ('DÉPARTEMENT MATHÉMATIQUES', 'DÉPARTEMENT MATHÉMATIQUES'), ('DÉPARTEMENT TECHNOLOGIE', 'DÉPARTEMENT TECHNOLOGIE')], max_length=100),
        ),
    ]
