# Generated by Django 5.0.2 on 2024-02-22 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isimm', '0008_alter_department_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='email_department',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='enseignant',
            old_name='nom',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='chef_department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='department',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='photo',
        ),
        migrations.AddField(
            model_name='department',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='department_covers/'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head', to='isimm.enseignant'),
        ),
        migrations.AddField(
            model_name='department',
            name='teachers',
            field=models.ManyToManyField(related_name='departments', to='isimm.enseignant'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='is_head_of_department',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_pics/'),
        ),
    ]
