# Generated by Django 5.0.2 on 2024-02-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isimm', '0009_rename_email_department_department_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='is_head_of_department',
        ),
    ]
