# Generated by Django 5.0.2 on 2024-02-23 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isimm', '0010_remove_enseignant_is_head_of_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='head_of_department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='teachers',
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
        migrations.DeleteModel(
            name='Matiere',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Enseignant',
        ),
    ]
