# Generated by Django 5.0.2 on 2024-02-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isimm', '0012_department_subject_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
